### ISSUE TITLE
Weird things in "Inputs to synthesis (default)"

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/germinator#101]
I've only glanced at it, but some trees do not have confirmed rooting (e.g. [1](https://tree.opentreeoflife.org/curator/study/view/ot_19/?tab=trees&tree=Tr63070), [2](https://tree.opentreeoflife.org/curator/study/view/ot_232/?tab=trees&tree=Tr49047)), some do not have "preferred" status (e.g. [1](https://tree.opentreeoflife.org/curator/study/view/pg_422/?tab=trees&tree=tree530)).

This [one](https://tree.opentreeoflife.org/curator/study/view/ot_232/?tab=trees&tree=Tr49047) has the off-putting tree name of "topology-similar to publication?".

Anyway, looks like this needs to be scrutinized.

**Comment by josephwb** [comment]
Oh, and some have missing inference methods.

**Comment by josephwb** [comment]
This [one](https://tree.opentreeoflife.org/curator/study/view/ot_530/?tab=trees&tree=Tr81397) has no specified ingroup whatsoever!

**Comment by josephwb** [comment]
Another [one](https://tree.opentreeoflife.org/curator/study/view/ot_331/?tab=trees&tree=Tr77751) with no ingroup and no confirmed rooting.

**Comment by josephwb** [comment]
Just a note: the "preferred" status is identified by the `ot:candidateTreeForSynthesis` property. This was only added to the `find_trees` query results recently (if that is what is being used).

**Comment by kcranston** [comment]
These are almost all cases where I assumed that the preferred tree in the study was the one that should be included, but in fact was not as well curated as another (non-preferred) tree. Hazards of manual curation. Getting this process better automated would help catch errors like these. So would having the treeID in the tree list, and having a validation test before adding trees to one of the synthesis collections. 

We aren't checking for missing inference methods before adding trees, so not surprised that is sometimes absent. We also aren't looking at tree labels. 

I've confimed rooting and added ingroup to the ones you note.

**Comment by josephwb** [comment]
Please note that I was not exhaustive; just glanced around. I left them un-fixed so your code might identify them. I am sure there are more without rooting/ingroup/etc.

**Comment by kcranston** [comment]
All of the issues with lack of ingroup and unconfirmed roots in that collection are now fixed. FYI, used [this script](https://github.com/OpenTreeOfLife/peyotl/blob/master/examples/collection_stats.py) to find them.
