### ISSUE TITLE
oti (neo4j) fails to start, but it doesn't wait for 120-second timeout

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/germinator#136]
See this [Gitter discussion](https://gitter.im/OpenTreeOfLife/public?at=59dcf46ff7299e8f53ce4850) for background and links to a bug tracker with the solution.

Short of upgrading Neo4j, or patching its control script in deployment, our temporary workaround is to downgrade `lsof` to an older version that's compatible. This seems reasonable, since we're transitioning away from Neo4j. But it's one more thing to keep track of.

**Comment by jimallman** [comment]
Just in case the above discussion is lost or just too confusing, [here's the neo4j issue](https://github.com/neo4j/neo4j/issues/3414) that pinpoints the problem with lsof >= 4.87

**Comment by bredelings** [comment]
The patch consists of replacing
`newpid=$(lsof -i :$NEO4J_SERVER_PORT -F T -Ts | grep -i "TST=LISTEN" -B1 | head -n1)`
with
` newpid=$(lsof -i :$NEO4J_SERVER_PORT -F T -Ts | grep "p")`
Also, the second line appears to work with earlier versions of lsof as well.

**Comment by jimallman** [comment]
> Also, the second line appears to work with earlier versions of lsof as well.

Yes, but note that this can return multiple lines (process ids), which seems problematic:
```bash
$ sudo lsof -i :7478 -F T -Ts | grep "p"
p1381
p2633
p2634
```

I gather the one we're interested in is listed closest to `TST=LISTEN` in the full output:
```bash
$ sudo lsof -i :7478 -F T -Ts
p1381
TST=LISTEN
p2633
TST=CLOSE_WAIT
p2634
TST=CLOSE_WAIT
```

**Comment by bredelings** [comment]
Oh, I see.

**Comment by jimallman** [comment]
I think this captures the sense of what we're looking for:
```bash
$ sudo lsof -i :7478 -F T -Ts | grep "TST=LISTEN" -B4 | grep "^p" | tail -n1
p1381
```
In other words:
  * gather process and file info for our desired port
  * filter for entries marked "TST=LISTEN", plus 4 lines before each (in case there are other TST= entries, which i've noticed in some lsof output)
  * filter for lines _starting_ with "p", and return just the last one

This should handle changes in order, multiple TST lines, etc.

**Comment by mtholder** [comment]
closing because of "won't fix"
