### ISSUE TITLE
Server redundancy

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#14]
The question of server redundancy came up recently after observations of long delays in the tree browser after or during API operations (did I get that right?). The attached figure is what I've come up with as a redundancy design. We can't, and probably don't need to, have redundant phylesystem servers. We can't, and probably don't need to, have redundant web2py servers: currently web2py manages our auxiliary files and that service has to be unique. But the three neo4j services can pretty easily be replicated, and they're the most resource intensive.

![replication](https://cloud.githubusercontent.com/assets/2035858/6061541/a7b1b24a-ad16-11e4-83aa-b344d9277c75.png)

This is just a sketch; don't accord too much meaning to the different kinds of boxes or paths that go through or not through boxes that have host names.

This shows two options, one with the api's neo4j instances in a common pool with the browser/curator's (a), and the other with one neo4j server dedicated to the api.

Each neo4j server would each have its own hardware, but the other pieces wouldn't all have to be physically distinct servers; some could be vhosts.

Comments?

**Comment by mtholder** [comment]
Seems fine to me. I don't know much about server load balancing. I agree on the point about not needing multiple versions for the web2py and phylesystem parts. Maybe not for OTI either?

I do think that the idea of creating a static file cache for the argusons (mentioned on https://github.com/OpenTreeOfLife/opentree/issues/558 ) may be worth pursuing. when I load the https://tree.opentreeoflife.org/opentree and look in the chrome dev tools it looks like the initial call to getSyntheticTree takes 1.5 sec (much of that is content download, and my location may explain some of that).  That is not terrible, but presumably serving up a gzipped version would be much snappier.

It seems a little wasteful to replicate servers just to serve 20G of content that is very rarely updated, when we could probably write a caching layer and fill the cache as part of deployment.

**Comment by jar398** [comment]
I agree about the caching, and this was the reason for trying to create GET
versions of the neo4j methods. That got mired in maven unhappiness, which
showed up in the most obscure possible way. Someone stronger than I could
have forged ahead and made it work. Doing a custom cache would work and
could be put in various locations. Web2py also has support for caching.
Another option would be to implement a GET wrapper for one or two neo4j
methods and then use apache caching on the front of that.

One question is whether we can afford to have the cache flushed on every
server restart, or if we really need something that will persist longer.

**Comment by mtholder** [comment]
while the general issue is still relevant, it seems like we are going to have to tackle this as we deploy the new otcetera-based services. So, it'll either arise there with new details or be fixed. So, closing this issue.
