### ISSUE TITLE
wrong user name for path to taxonomy cgi script on frontend machines

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/germinator#161]

**Comment by mtholder** [comment]
Lines in /etc/apache2/opentree-shared.conf should be:

        Alias "/taxonomy/browse" "/home/opentree/repo/opentree/taxonomy/cgi-bin/browse.py"

        <Directory "/home/opentree/repo/opentree/taxonomy/cgi-bin">

, but had `otcetera` rather than `opentree` after deploy.

**Comment by jimallman** [comment]
OK to repeat this hot fix in the germinator code, and just assume the `/home/opentree/` path? It looks like this means skipping [this sed operation](https://github.com/OpenTreeOfLife/germinator/blob/78c800288631fa4e06efa160e1c3b1c06049cf5b/deploy/restart-apache.sh#L52), but still populating the temp file.
