### ISSUE TITLE
Question: will the synthetic tree be updated again?

### ISSUE THREAD

**Issue by cleopatra17** [OpenTreeOfLife/germinator#163]
First of all, thanks for the tremendous and unprecedented work. I'm currently working on yet another visualisation of your tree and was wondering, will there be any updated synthetic tree in the near future? It seems the last one was from 2019, and it includes some bugs to be fixed (eg lack of Homo sapiens sapiens).
Thanks

**Comment by mtholder** [comment]
Hi, We do plan to have an updated trees soon (in the next week or two). thanks for the interest in the project. Mark

**Comment by cleopatra17** [comment]
Wow perfect timing. Thanks @mtholder
