### ISSUE TITLE
Site monitoring

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#17]
We need to be running nagios or something similar, so that we're the ones to discover outages rather than our users.
Trello card: https://trello.com/c/49dLpVfA

**Comment by mtholder** [comment]
Closing because we have nagios, though I would like to be added to the "nag this person on outages" list

**Comment by jar398** [comment]
I've added you to the nagios configuration. Feel free to test it to make sure, e.g. by turning off any dev service for at least 10 minutes.
