### ISSUE TITLE
Neo4j phones home

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#21]
Considered very bad manners for an installed app. Is there a way to turn it off?

<img width="600" alt="neo4j-phones-home" src="https://cloud.githubusercontent.com/assets/2035858/8729347/aa99c382-2bb8-11e5-80ee-fcb1671a541d.png">

**Comment by mtholder** [comment]
seems very unlikely, that any of this will answer this, so closing...
