### ISSUE TITLE
Updates for phylesystem and synthesis statistics

### ISSUE THREAD

**Issue by pmidford** [OpenTreeOfLife/germinator#25]
Four minor changes:

Change date format to eliminate hours (@jimallman's code ignores hours, so not high priority)

Change json writing in phylesystem and synthesis stats to avoid breaking the json file if interrupted (e.g., by filesystem full errors, as happened in July).

Do we report counts of unmapped OTUs (the wiki page says we should, but @jar398 suggested they aren't important).

Report OTT version in synthesis stats based on API call.

These are all implemented, but I'm waiting on the pull request for a decision what to include.

**Comment by mtholder** [comment]
don't see a PR, so assuming that we forgot to close this...

**Comment by jimallman** [comment]
Yes, it looks like these changes were actually merged as PRs #26 and #27.
