### ISSUE TITLE
Strange jump in OTU count in current stats

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/germinator#28]
In the current [Progress page on devtree](https://devtree.opentreeoflife.org/about/progress), there's an unexpected jump in "OTUs in phylesystem, but not in synthesis":

![screen shot 2015-08-21 at 12 55 03 pm](https://cloud.githubusercontent.com/assets/446375/9414099/e634423e-4803-11e5-9c99-6a9fa64462e4.png)

![screen shot 2015-08-21 at 12 55 11 pm](https://cloud.githubusercontent.com/assets/446375/9414100/ec105be8-4803-11e5-82b3-bc7f58def8ce.png)

This looks like a glitch in the `phylesystem.json` on ot16, which has a sudden drastic increase in the `unique_OTU_count` field. Here's the entry for Jan 5, 2015:
```json
  "2015-01-05": {
    "OTU_count": 437683,
    "nominated_study_OTU_count": 435196,
>>  "unique_OTU_count": 163696,
    "unmapped_OTU_count": 46699,
    "nominated_study_count": 2873,
    "nominated_study_unmapped_OTU_count": 46573,
    "nominated_study_unique_OTU_count": 163205,
    "reported_study_count": 3044,
    "study_count": 2881,
    "run_time": 12.01783299446106
  }
```
...and the next entry, for Feb 1, 2015:
```json
  "2015-02-01": {
    "nominated_study_OTU_count": 422849,
>>  "unique_OTU_count": 418832,
    "OTU_count": 422849,
    "nominated_study_count": 2726,
    "run_time": 1836.8633618354797,
    "nominated_study_unique_OTU_count": 418832,
    "reported_study_count": 2895,
    "study_count": 2727
  }
```

The change in schema (number and names of fields) suggests that the later stats were generated by a different version of the synth-stats gathering tool, so this might be a one-time problem. This discontinuity does not appear in the stats from my local test server (provided by @pmidford), which might be correct but don't have the latest records.

**Comment by jimallman** [comment]
@pmidford, perhaps this glitch was a side effect of the [surgery done after this file was truncated](https://github.com/OpenTreeOfLife/opentree/commit/c575e490a281fda1d361238bec70d226b5adb15e#commitcomment-12477682)? 

In any case, the more sensible-looking data on my local server was [your recently generated `production.json` file mentioned in this IRC exchange](http://irclog.perlgeek.de/opentreeoflife/2015-08-16#i_11065191). Does it make sense to use this on devtree, replace the funky file above?

**Comment by jimallman** [comment]
To be clear, I renamed `production.json` to `phylesystem.json` on my local server, and would of course do the same on devtree. Also, this file does include an entry for August 2015, so it's up to date.

**Comment by pmidford** [comment]
Yes, since the generated file came out of git, I'd be more confident
about that data.

**Comment by pmidford** [comment]
The only question about devtree is whether the phylesystem-0 repo represents devtree development and how far back.  With the history scripts we can generated from a different repo if appropriate.

**Comment by jimallman** [comment]
Yes, phylesystem-0 is the Nexson repo for devtree. But my current intention is to _ignore_ stats gathered from devtree and show only production stats, even on the devtree Progress page (mostly to catch errors like the one above, without being distracted by the weird history of the dev site).

**Comment by pmidford** [comment]
Then we're fine.  We run the chron job on production once a month.  If we ever encounter a discrepancy, we can validate by regenerating from the history and stop worrying about the dev repo.

**Comment by jimallman** [comment]
OK, I've moved the latest production `phylesystem.json` to devtree. (If we want to examine the old/glitchy file further, it's saved there as `GLITCH-phylesystem.json`.)

**Comment by jimallman** [comment]
I'll close this issue, but we should review the workflow for adding stats over time to make sure that we're

- building on the existing data, including any manual tweaks, nad
- keeping proper backups (or committing these to Github)
