### ISSUE TITLE
Need documentation for interface between propinquity and clients such as tm-lite 

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#40]
I presume it's a set of files with special names. I realize there is documentation at https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs-v3 (update: moved to https://github.com/OpenTreeOfLife/opentree/wiki/Conflict-and-synthesis-file-formats), but this is missing information on file names and formats and directory structure, and I'm not sure that it's otherwise complete and up to date.

This documentation will be useful for (a) architecture review, (b) anyone trying to understand the system, (c) any new producers of trees that want to use tm-lite, (d) any new consumers of trees produced by propinquity.

I would prefer three documents eventually: one for the web API, a separate one for the file-based interface, and one with information that applies to both, and is invoked by reference.

New documentation files should go in the germinator repo.

@bredelings I'm assigning this to you but @josephwb and @mtholder are obviously also involved. And I can help to the extent I have or can find the needed knowledge.

See comments at https://github.com/OpenTreeOfLife/treemachine/issues/197

**Comment by jar398** [comment]
I guess it's not just tm-lite; another output that needs to be documented is the subproblems, which in the past we have treated as important enough that they need to be made available.

Let me elaborate a bit: there are going to be scripts (such as the deployment system) that want to refer to a bundle of synthesis outputs using a single token, such as 'draftversion5.0'.  From that token one has to be able to get to all the outputs in a standard way.  For example, 'draftversion5.0' could be a directory name and every such directory would contain a fixed set of file names. This is how the taxonomy works. We would need to document that list of names, if that's the approach to be taken. There are other ways it might be done.

It would be lovely to have prospective documentation that can be reviewed and improved, rather than retrospective documentation saying how it got done.

**Comment by jar398** [comment]
There's also this: https://docs.google.com/document/d/1BLi44ar-lvfN8VbuQjc1p4Vg-E2tVy-_HXl8k439Goo/edit  which is a README in a directory of sample files.

**Comment by jar398** [comment]
Related to this: https://github.com/OpenTreeOfLife/treemachine/issues/184
If the subproblems are available and there is a little documentation, then anyone can write such a service.

**Comment by jar398** [comment]
@bredelings This really needs to be done this week, since I am trying to figure out what the web API should look like and it gets its information from propinquity output, and we're trying to release API v3 this month. Are you waiting for me to do something? If so what should I do?

**Comment by jar398** [comment]
The following is close to being the answer to this issue:
https://github.com/OpenTreeOfLife/opentree/wiki/Conflict-and-synthesis-file-formats
which I updated by doing some reverse engineering, but I will not have confidence in it until some of the gaps are filled, and @bredelings reviews it and says it's accurate and complete.

**Comment by mtholder** [comment]
See https://github.com/OpenTreeOfLife/propinquity/issues/10 for a proposal for syntax for some new information that should be flowing from synth to tm-lite.

**Comment by jar398** [comment]
I'm still not aware of a document describing the directory structure and file names. It could be reverse engineered from something like http://phylo.bio.ku.edu/ot/next-synth/index.html
which I guess will have to serve as documentation for now.

Only the two files (newick and annotations) are needed by tm-lite (and by the deployment system, once it is taught how to invoke tm-lite), so if there's unwillingness to commit, maybe at least we can commit to the paths to those two files?  I would rather write deployment system improvements against a document (wiki page) describing this interface, rather than an automatically generated index.html that is overwritten on each propinquity run.

(and anyhow shouldn't the index.html hyperlink to the [documentation for the annotations file](https://github.com/OpenTreeOfLife/opentree/wiki/Conflict-and-synthesis-file-formats)?)

Maybe this issue should be assigned to @mtholder  ?

**Comment by kcranston** [comment]
The propinquity README has an [artifacts section](https://github.com/OpenTreeOfLife/propinquity#artifacts) with links to detailed information about all of the outputs. Is this sufficient? If not, what do you want?

**Comment by jar398** [comment]
I am looking for stable documentation that generalizes across all runs of propinquity and that lives in a non-ephemeral location. Otherwise it will just seem like a moving target. If it's OK for me to copy the README to the wiki, that would do the trick.

**Comment by kcranston** [comment]
That README is stable, and each link in the artifacts section is to a stable README in a subdirectory of the repo. It all exists outside of the propinquity output or any specific propinquity run.

**Comment by jar398** [comment]
Assuming you mean https://github.com/OpenTreeOfLife/propinquity/blob/master/README.md , I will take that as the answer to the request.
