### ISSUE TITLE
Prepare v3 web API documentation in wiki

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#41]
* Combine the v2 API wiki page with the v3 API google doc to yield new wiki page
* Move material in the current v3 API wiki page to a wiki page with a more appropriate name
* Release notes wiki page describing v2/v3 differences

**Comment by jar398** [comment]
So far:
* https://github.com/OpenTreeOfLife/germinator/wiki/Release-notes-for-web-API-v3
* https://github.com/OpenTreeOfLife/germinator/wiki/Open-Tree-of-Life-Web-APIs
* https://docs.google.com/document/d/17cGJMHBUpofow8-f9ezMyNnMhAwS33xkGlUwicsKNVM/edit#heading=h.hgd5s7mffsp1

**Comment by mtholder** [comment]
I think it is worth considering deploying the new tree and tm-lite somewhere for the workshop (conditional on the fact that we have some confidence that tree services and the web app are working). 

We could use a new pair of machines (testapi and testtree, perhaps) that we could have workshop participants use. We could deploy only tm-lite to testapi and use the v2 api.opentreeoflife.org for the other services if we wanted to keep the testapi instance slim.

The advantages:
  1. it would be nice to have the latest tree available.
  1. It would be nice if the feedback issues created at the workshop did not use the unstable neo4j node IDs
  1. it would be nice if scripts written at the workshop worked for more than a couple of weeks. some of them wouldn't given that we are about to break the v2 api.

Obviously, there is not a lot of time before the workshop, so I understand that we may not be able to pull it off.

**Comment by jar398** [comment]
I will create a new issue so that we have an appopriate place to discuss
deployment.​

**Comment by jar398** [comment]
Related: newick documentation https://github.com/OpenTreeOfLife/treemachine/issues/147 , https://github.com/OpenTreeOfLife/germinator/issues/13

**Comment by kcranston** [comment]
Superseded by #59
