### ISSUE TITLE
Update ArguSON v3 documentation

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#45]
@josephwb @jimallman - I went over the arguson doc and cleaned it up, making the names more consistent with the rest of the API and making some minor suggestions, which I've noted.  If you all could update this where necessary to match the implementation (and/or vice versa) I would appreciate it. If you disagree with this let's talk, e.g. if making so many name changes is a burden you don't want to take on. But it may be a long time before we get this chance again.

Draft here: https://github.com/OpenTreeOfLife/germinator/wiki/%22Arguson%22-format

**Comment by jimallman** [comment]
> if making so many name changes is a burden you don't want to take on

From the client-side POV, it's probably more efficient to make any name changes all at once, since the testing burden is the same either way. So far, this looks good to me, but here are a few questions and suggestions:

- Regarding `node_id` versus `ot_node_id`, the former makes sense to me. The latter looks like an OT Taxonomy id, and I don't see the benefit of a prefix if it's a node id in the synthetic tree (not "borrowed" from elsewhere). 

- Can we add a URI (vs CURIE) to the example list for `tax_sources`? I'd do it myself, but I don't know what a credible-looking URI would be here.

**Comment by jar398** [comment]
Good idea for an example, I'll add one.  There is actually one already in
OTT: https://en.wikipedia.org/wiki/Homo_sapiens_sapiens  which is pretty
weak but it's all I could find.  I'll just put
http://dx.doi.org/10.1186/1471-2148-14-23  which doesn't occur but might.

**Comment by jar398** [comment]
Just reviewed the taxonomy/taxon method for consistency with arguson and we have a few problems (if we care about consistency).
* taxon has "rank", arguson has "tax_rank" (either is fine with me)
* taxon has "unique_name", arguson has "uniqname" ("unique_name" probably better; this is easily fixed in arguson)
* taxon has "ottID", arguson has "ott_id" (I prefer "ott_id" - that would be a change in taxon method)
* taxon documentation has integer "node_id" but this is going away, if it hasn't already gone away

And regarding uniqname, I added the following comment to the wiki page: "not clear why this [uniqname] would be in the brief node but not in non-brief nodes. It should be in both or neither. if not used by tree browser, I suggest neither. If it is used, then maybe it should be optional when the uniqname is the same as the name."

**Comment by jimallman** [comment]
> taxon has "rank", arguson has "tax_rank" (either is fine with me)

:+1: for `tax_rank` (since this is borrowed from taxonomic sources and not properly "of" the synthetic tree)

> taxon has "unique_name", arguson has "uniqname"

:+1: for `unique_name` (unless "uniqname" is conventional?). FWIW, the word "uniqname" doesn't appear in any of the webapp code, so this field is currently not needed, but perhaps another caller would want it?

**Comment by jimallman** [comment]
> Good idea to add example URL, I'll add one.

@jar398 I cleaned up a funky delimiter (run-on code section) in your edit. Currently the example list is `["ncbi:123", "h2007:", "http://dx.doi.org/10.1186/1471-2148-14-23"]`. 

I gather `h2007:` is a naked QName; is that a valid CURIE by itself?

**Comment by jar398** [comment]
Hmm, another puzzle is that the rest of the tree_of_life API has OTT ids as integers, not strings. We should make this consistent somehow.

**Comment by jar398** [comment]
Good question. If you trace the grammar it seems to say that there *must*
be a / following the : , which is obviously wrong.

I thought foo: was ok since SPARQL supports it - and Turtle is supposed to
be consistent with SPARQL so I thought it was there too. And it's terribly
convenient. I guess this needs further investigation - I will have to
either find a different reference, or write to the RDF list asking for an
erratum.

```curie      ::=   [ [ prefix ] ':' ] referencereference   ::=
irelative-ref (as defined in [RFC3987
<https://www.w3.org/TR/2011/WD-rdfa-core-20110331/#bib-RFC3987>])

irelative-ref  = irelative-part [ "?" iquery ] [ "#" ifragment ]

   irelative-part = "//" iauthority ipath-abempty
                       / ipath-absolute

ipath-absolute = "/" [ isegment-nz *( "/" isegment ) ]

```

**Comment by jar398** [comment]
Update: that was the wrong spec.  Fixing to reference https://www.w3.org/TR/rdfa-syntax/#dfn-curieoriri .

**Comment by josephwb** [comment]
"uniqname" is taken from the header of the taxonomy tsv file. I will update it in treemachine.

**Comment by kcranston** [comment]
[done](https://github.com/OpenTreeOfLife/germinator/wiki/%22Arguson%22-format).

**Comment by jar398** [comment]
Overtaken by #59
