### ISSUE TITLE
Deploy API v3

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#47]
Issue created for discussion of release plans. Checkmark means ready for review.

 - [x] Spec #48 
 - [x] Tests
 - [x] Documentation #59
 - [x] Implementation (including client updates)
 - [x] New tree files to files.opentreeoflife.org
 - [x] Deploy to devtree / devapi
 - [x] Beta test
 - [x] Release notes
 - [ ] Announce
 - [ ] Deploy to production

The release plan I prepared is here: https://docs.google.com/document/d/17cGJMHBUpofow8-f9ezMyNnMhAwS33xkGlUwicsKNVM/edit#

but maybe it will be better to discuss on a github issue instead of a google doc.

That google doc has links to a number of issues related to deployment.

I just added tests as a to-do to that file. We need at least minimal tests for tm-lite and taxomachine.

Some apache redirects for /v3/ URLs are in place, see #46

**Comment by jar398** [comment]
@mtholder said on #41 : (please respond on this issue, not there)

I think it is worth considering deploying the new tree and tm-lite somewhere for the workshop (conditional on the fact that we have some confidence that tree services and the web app are working).

We could use a new pair of machines (testapi and testtree, perhaps) that we could have workshop participants use. We could deploy only tm-lite to testapi and use the v2 api.opentreeoflife.org for the other services if we wanted to keep the testapi instance slim.

The advantages:

it would be nice to have the latest tree available.
It would be nice if the feedback issues created at the workshop did not use the unstable neo4j node IDs
it would be nice if scripts written at the workshop worked for more than a couple of weeks. some of them wouldn't given that we are about to break the v2 api.
Obviously, there is not a lot of time before the workshop, so I understand that we may not be able to pull it off.

**Comment by jar398** [comment]
I put a checklist in the issue description. Spec was #48. Tests are mostly done; I need to update taxonomy and tnrs API tests to match the updated spec. We might want to spin out some more issues if we need to discuss documentation and release notes.

**Comment by kcranston** [comment]
Created an issue to track status of documentation: #59 

Would be helpful to have similar issues to track status of methods, tests, and implementation. It's hard to know when to file issues about things being broken without knowing what is ready for testing (e.g. see #57 ).
