### ISSUE TITLE
handling incompatible parameter combos in subtree method

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/germinator#54]
In addition to node_id / ott_id, the `tree_of_life/subtree` method in the spec has three parameters:
* `format`: string,  one of "newick" or “arguson”; default=”newick”
* `label_format`: string  (for newick only); one of “name”, “id”, or “name_and_id”; default = “name_and_id”
* `height_limit`: integer   e.g. 3  -- for arguson. Default 5

How should we handle incompatible parameter combinations: (format=newick, height_limit=3) or (format=arguson, label_format=id)? Quietly ignore them? Error message?

**Comment by jimallman** [comment]
I'm thinking about command-line tools with many arguments. IIR, there are often some arguments that are dependent on others to have any effect. (I can come up with some examples if you like.) This seems like precedent for having newick-only and arguson-only args, with no ill effect if they're used in the wrong "context."

**Comment by jar398** [comment]
@jimallman there's a name for what you describe, with a very distinguished
pedigree: https://en.wikipedia.org/wiki/Dependent_type

**Comment by josephwb** [comment]
Truncated newick is implemented.

**Comment by josephwb** [comment]
And deployed on test.

**Comment by kcranston** [comment]
Truncated newick? Where did we agree on that?

**Comment by josephwb** [comment]
@jar398 left that in a comment as the preferred route.

**Comment by jar398** [comment]
Just because *I* prefer it does not mean it's now part of the spec. It was
just a remark in the middle of a discussion with you.

All changes to the spec should at this point go through issues so that they
get visibility.

**Comment by josephwb** [comment]
...
You said this was a compatible change. You mentioned it would reduce the documentation burden. Where did you give any indication that it shouldn't be done?

**Comment by mtholder** [comment]
Can we agree that there are no objections to silently ignoring options that are
  1. provided by the client as arguments, but which
  2. the spec says do not apply because of other arguments
?

That seems uncontroversial to me, so I'm tempted to close this issue.

**Comment by jar398** [comment]
I disagree with your claim that it is uncontroversial, and can't think of a
reason why you would want to fail to reject an unsatisfiable request (e.g.
a request for a tree with height no greater than 4). Silent failure instead
of error may be common among programmers (as in shell command arguments)
but it goes against what I have learned over the years about how to build
robust systems.

But it's a very small controversy in this case and I'm not going to push.

**Comment by josephwb** [comment]
Soooo... keep the truncated newick in there, or not? Seems like people could use it to paste together smaller trees if the full tree is too large.

**Comment by jar398** [comment]
I'll open a new issue for this - it's really a separate question
