### ISSUE TITLE
Expose height_limit parameter for newick? (subtree method)

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#55]
height_limit is implemented for newick, but the spec says it isn't. I had not expected this feature to get implemented, and it is not necessary for the v3 release, but as it is there and it has some utility, I think we should consider it.

This issue is split off from #54.

I think it's probably a good idea, but I wonder if the design is complete.  For example, how does a client distinguish tips in the returned tree that are tips in the synthetic tree, from tips that are tips only because the height limit was reached?

One option is to delay discussion. I'm content with leaving it out now and maybe adding it to a v3 point release.

**Comment by josephwb** [comment]
It _doesn't_ say not for newick It says:
>height_limit : integer   e.g. 3  -- for arguson

Label format, on the other hand, is explicit:
>label_format: string   for newick only

**Comment by josephwb** [comment]
From api doc:
>height_limit could be applicable to newick, if we get around to implementing height-limited newick in time; this would be preferred since it's cleaner and has lower documentation burden.

**Comment by mtholder** [comment]
If this feature is working, then it makes sense to me to include it. We could add an additional field to the response to list the tips that were the slice points in the event that the height limit is triggered. Even without that info, a client could use this service (because they could check for the tips returned in the taxonomy).

**Comment by josephwb** [comment]
It seems like "feature is working" has no bearing on things. But I agree with your other points.

**Comment by kcranston** [comment]
Couple of questions:
* is the default value for height limit the same for format=newick and format=arguson? 
* can a user request a newick subtree without a height limit
* how should the webapp decide whether to provide the 'download tree as newick' link? It currently sets a limit on the number of tips based on no height limit. If the number of tips is too large, should the webapp offer a height-limited newick string?

**Comment by josephwb** [comment]
Default for arguson is 5. Default for newick is -1 (that is, no limit).

**Comment by josephwb** [comment]
Here is an example call (_don't worry_: `newickDepth` is temporary):
```
curl -X POST https://test.opentreeoflife.org/v3/tree_of_life/subtree -H "content-type:application/json" -d '{"node_id":"ott81461", "label_format":"name", "height_limit":3}'
{
  "newickDepth" : 3,
  "newick" : "(((Struthionidae)Struthioniformes,(Rheiformes,mrcaott165688ott167137)mrcaott165688ott857860)Palaeognathae,((Crecopsis_egregia)Crecopsis,(Nesophylax_ater)Nesophylax,(Edithornis_sylvestris)Edithornis,(Cabalus_modestus)Cabalus,Palaeorallus,Parvirallus,Latipons,Eocrex,(Dryolimnas_cuvieri)Dryolimnas,(Aenigmatolimnas_marginalis)Aenigmatolimnas,(Cyanolimnas_cerverai)Cyanolimnas,(Diaphorapteryx_hawkinsi)Diaphorapteryx,(Atlantisia_podarces,Atlantisia_rogersi)Atlantisia,(Neocrex_colombianus,Neocrex_colombiana,Neocrex_erythrops)Neocrex,(Rougetius_rougetii)Rougetius,(Gymnocrex_rosenbergii,Gymnocrex_talaudensis,Gymnocrex_plumbeiventris,Gymnocrex_plumbiventris)Gymnocrex,(Aphanapteryx_leguati,Aphanapteryx_bonasia)Aphanapteryx,Eurostopodus_guttatus,Eurostopodus_archboldi,Eurostopodus_temminckii,Eurostopodus_diabolicus,(Lewinia_mirificus,Lewinia_muelleri,Lewinia_mirifica,Lewinia_pectoralis)Lewinia,(Nesoclopeus_poecilopterus,Nesoclopeus_woodfordi)Nesoclopeus,(Micropygia_schomburgkii)Micropygia,(Gallicrex_cinerea)Gallicrex,(Crex_egregia,Crex_crex)Crex,(Megacrex_inepta)Megacrex,(Pardirallus_nigricans,Pardirallus_maculatus,Pardirallus_sanguinolentus)Pardirallus,(Canirallus_oculeus,Canirallus_beankaensis,Canirallus_kioloides)Canirallus,(Cladorhynchus,Recurvirostra,Himantopus)Recurvirostridae,(Coturnicops_notatus,Coturnicops_exquisitus,Coturnicops_noveboracensis)Coturnicops,(Stercorarius)Stercorariidae,(Rallina_leucospila,Rallina_tricolor,Rallina_forbesi,Rallina_canningi,Rallina_fasciata,Rallina_rubra,Rallina_mayri,Rallina_eurizonoides)Rallina,(Habroptila_wallacei,Habroptila_wallacii)Habroptila,(Mancalla,Miocepphus,mrcaott385981ott855480,Cyclorrhynchus,mrcaott147723ott280897)Alcidae,(Aramides_wolfi,Aramides_saracura,Aramides_mangle,Aramides_calopterus,Aramides_cajaneus,Aramides_cajanea,Aramides_ypecaha,Aramides_axillaris)Aramides,(Amaurolimnas_concolor)Amaurolimnas,(Aramidopsis_plateni)Aramidopsis,(Amaurornis_bicolor,Amaurornis_isabellinus,Limnocorax_flavirostra,Amaurornis_moluccana,Amaurornis_phoenicurus,Amaurornis_flavirostra,Amaurornis_isabellina,Amaurornis_magnirostris,Amaurornis_akool,Amaurornis_olivieri,Amaurornis_olivacea)Amaurornis,(Eulabeornis_tricolor,Eulabeornis_castaneoventris)Eulabeornis,(Smutsornis,Pluvianus,Cursorius,Glareola,Stiltia,Rhinoptilus)Glareolidae,(Chionis)Chionididae,(Anurolimnas_fasciatus,Anurolimnas_viridis,Anurolimnas_castaneiceps)Anurolimnas,(Carbo,Mesocarbo,Microcarbo,mrcaott9830ott480885)Phalacrocoracidae,(Anseriformes,Galliformes)Galloanserae,(mrcaott5481ott17146,mrcaott246ott5021)mrcaott246ott5481)Neognathae)Aves;"
}
```

**Comment by jar398** [comment]
Where the spec says "-- for arguson" that implies, in a Gricean way, that it is not for newick. That is, why would it say "for arguson" if it were intended to also apply to newick? So we are discussing a spec change here, and at this point in the process there should be a heavy bias against any spec change.

That said, I'm in favor of changing the spec so that the height_limit is applicable to all output formats. (I would probably not be in favor if it were up to me to make the implementation conform to the spec change, or if someone had produced another argument against.)

I suspect we've implicitly adopted the change, so this may be moot, but the issue needs to be closed out somehow.

Re @kcranston's questions:

 * having different height limits is sort of unfortunate, but I don't think it matters a lot. I understand why Joseph did what he did and I have no particular opinion on it one way or the other.
 * can request no height limit? yes, -1
 * good question but I don't think it's relevant to the question at hand, which is what the API spec should say. We could think about adding new API features to support the webapp better, but this is not a good time or place for that.

**Comment by kcranston** [comment]
I think this is now done, so closing.
