### ISSUE TITLE
Extra (or undocumented) returns values from 

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/germinator#56]
A successful JSON response from `/v3/tnrs/autocomplete_name` includes more information that is shown in [the v3 API documentation](https://docs.google.com/document/d/1XcgoQGJVxSgk-yKB-NAayQNZ2_QUQuw9_RIvbR2LeTw/edit#heading=h.w0pn3jxhaqq0), specifically

 - `ot:ottId` (seems to be a duplicate of `ott_id`)
 - `is_dubious` (should be `is_suppressed`)
 - `node_id` (where does this come from!?)

```bash
curl 'https://test.opentreeoflife.org/v3/tnrs/autocomplete_name'  \
  -H 'Content-Type: application/json'  \
  --data-binary '{"name":"Homini","context_name":"All life"}'

[ {
  "unique_name" : "Hominidae",
  "ot:ottId" : 770311,
  "ott_id" : 770311,
  "is_dubious" : false,
  "is_higher" : true,
  "node_id" : 2604818
}, {
  "unique_name" : "Homininae",
  "ot:ottId" : 312031,
  "ott_id" : 312031,
  "is_dubious" : false,
  "is_higher" : true,
  "node_id" : 2604821
}
```

**Comment by josephwb** [comment]
@jimallman This is tnrs, so not me.

**Comment by jar398** [comment]
New version of v3 API deployed on devapi and test. Please check expected
operation and close issue if satisfied.​

**Comment by kcranston** [comment]
This seems to be working as expected now.
