### ISSUE TITLE
Unexpected return values from /v3/taxonomy/mrca

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/germinator#57]
The [spec](https://docs.google.com/document/d/1XcgoQGJVxSgk-yKB-NAayQNZ2_QUQuw9_RIvbR2LeTw/edit#heading=h.kpaht16u06zu) says we should expect an [extended-taxon-blob](https://docs.google.com/document/d/1XcgoQGJVxSgk-yKB-NAayQNZ2_QUQuw9_RIvbR2LeTw/edit#heading=h.lqnszlqrajj0), but the actual returned object is a bit different. 
```bash
curl 'https://test.opentreeoflife.org/v3/taxonomy/mrca'  \
  -H 'Content-Type: application/json; charset=UTF-8'  \
  --data-binary '{"ott_ids":[610934,526649,886239,412039,3599201,886238,283263,127704,179650,411522,937192,3599176,3599208,857822,1059191,1039403,1059189,1039400,462405,487015,683056,311607,412036,412035,379424,863640,232059,1039405,474279,462404,1039402,462406,227577],"include_lineage":false}'

{
  "taxon" : {
    "tax_sources" : [ "ncbi:28728", "worms:225852", "gbif:5291", "irmng:104233" ],
    "unique_name" : "",
    "synonyms" : [ "Tyrannidae" ],
    "name" : "Tyrannidae",
    "flags" : [ "SIBLING_HIGHER" ],
    "ott_id" : 187371,
    "rank" : "family"
  },
  "ott_ids_not_found" : [ ]
}
```

Here's what I think should change:
 - change `taxon` to `mrca` to match the spec
 - add `is_suppressed` to the extended-taxon-blob (or mark this as optional in the spec)
 - confirm that `ott_ids_not_found` should be present (add this to the spec?)

**Comment by jimallman** [comment]
Or maybe the existing 'taxon' should be a sub-property of 'mrca'? It's not clear from the spec, but this is the structure returned by /v3/tree_of_life/mrca:
```
{
  "mrca" : {
    "taxon" : {
      "tax_sources" : [ "ncbi:9126", "worms:159384", "gbif:729", "irmng:11290" ],
      "unique_name" : "Passeriformes",
      "name" : "Passeriformes",
      "rank" : "order",
      "ott_id" : 1041547
    },
    "num_tips" : 8420,
    "node_id" : "ott1041547"
  }
}
```

**Comment by jar398** [comment]
I'm in the middle of fixing the v3 taxonomy API.  Should be ready later
today.

​

**Comment by jar398** [comment]
New version of v3 API deployed on devapi and test. Please check expected
operation and close issue if satisfied.
​

**Comment by kcranston** [comment]
It looks like this is still returning `ott_ids_not_found`, i.e. the code doesn't match the spec. Example call:

`curl -X POST https://test.opentreeoflife.org/v3/taxonomy/mrca -H 'content-type:application/json' -d '{"ott_ids":[515698,590452,409712,643717]}'`

returns

```
{
  "mrca" : {
    "is_suppressed" : false,
    "tax_sources" : [ "ncbi:4209", "worms:234044", "gbif:414", "irmng:10011" ],
    "unique_name" : "Asterales",
    "synonyms" : [ ],
    "name" : "Asterales",
    "flags" : [ ],
    "ott_id" : 1042120,
    "rank" : "order"
  },
  "ott_ids_not_found" : [ 409712 ]
}
```

**Comment by kcranston** [comment]
Along with the change to either the code or the spec, it looks like we need a change to the test as well, since this should have failed.

**Comment by jar398** [comment]
There is no test that checks for a 400 response for mrca with unknown OTT
id. There should be one; making one hereby becomes part of this issue.

There is a test for induced_subtree and 400.  The test is failing, but the
API is doing the right thing, so there is a bug in the test.

Related: https://github.com/OpenTreeOfLife/treemachine/issues/204

**Comment by jimallman** [comment]
The output (versus original comment above) looks good now:
```bash
curl 'https://test.opentreeoflife.org/v3/taxonomy/mrca'  \
  -H 'Content-Type: application/json; charset=UTF-8'  \
  --data-binary '{"ott_ids":[610934,526649,886239,412039,3599201,886238,283263,127704,179650,411522,937192,3599176,3599208,857822,1059191,1039403,1059189,1039400,462405,487015,683056,311607,412036,412035,379424,863640,232059,1039405,474279,462404,1039402,462406,227577],"include_lineage":false}'

{
  "mrca" : {
    "is_suppressed" : false,
    "tax_sources" : [ "ncbi:28728", "worms:225852", "gbif:5291", "irmng:104233" ],
    "unique_name" : "Tyrannidae",
    "synonyms" : [ ],
    "name" : "Tyrannidae",
    "flags" : [ "SIBLING_HIGHER" ],
    "ott_id" : 187371,
    "rank" : "family"
  }
}
```
Leaving this issue open due to other concerns above.

**Comment by jar398** [comment]
I think everything is settled and working. Just waiting for me to add a test for the 400 that is already being returned.

**Comment by jimallman** [comment]
> There is a test for induced_subtree and 400.  The test is failing, but the API is doing the right thing, so there is a bug in the test.

Is this still the case? I couldn't find a test for `induced_subtree` outside of `test.sh` (which I've updated to work with the v3 APIs).

**Comment by jar398** [comment]
Are you looking at taxomachine or tm-lite?​

I may have fixed the test. Hard to keep track with so much going on.

**Comment by jar398** [comment]
All the v3/taxonomy tests pass on devapi, and I believe the tests agree
with the spec.  So I think we can close this...

**Comment by jimallman** [comment]
Agreed.
