### ISSUE TITLE
Extra (or undocumented) returns values from /v3/tnrs/match_names

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/germinator#58]
Lots of extra fields in the response [compared to the spec](https://docs.google.com/document/d/1XcgoQGJVxSgk-yKB-NAayQNZ2_QUQuw9_RIvbR2LeTw/edit#heading=h.cpva6qdxlm3x). I see `includes_dubious_names` in the main response body, plus a mix of old and new field names in the `matches` structure:
```
    "matches" : [ {
      "matched_node_id" : 2571416,
      "synonyms" : [ "Nectarinia fuelleborni", "Cinnyris mediocris fuelleborni", "Cinnyris fuelleborni" ],
      "flags" : [ ],
      "ott_id" : 4131373,
      "ot:ottTaxonName" : "Cinnyris fuelleborni",
      "search_string" : "nectarinia fuelleborni",
      "matched_name" : "Nectarinia fuelleborni",
      "is_synonym" : true,
      "score" : 1.0,
      "unique_name" : "Cinnyris fuelleborni",
      "ot:ottId" : 4131373,
      "is_deprecated" : false,
      "name" : "Cinnyris fuelleborni",
      "nomenclature_code" : "ICZN",
      "is_approximate_match" : false,
      "rank" : "",
      "is_dubious" : false
    } ]
```

**Comment by josephwb** [comment]
@jimallman This is tnrs, so not me.

**Comment by jar398** [comment]
I'm in the middle of fixing the v3 tnrs API.  Should be ready later today.

**Comment by jimallman** [comment]
Apologies to you both for my hasty (mis)assignment.

**Comment by jar398** [comment]
@jimallman Please confirm expected v3 operation, and close this issue at
your leisure.

**Comment by kcranston** [comment]
The results on test now match the spec and the docs. Closing.
