### ISSUE TITLE
description / return value of weburl in taxonomy/about

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/germinator#61]
The [current documentation](https://github.com/OpenTreeOfLife/germinator/wiki/Taxonomy-API-v3#about_taxonomy) for the `taxonomy/about` service states that the `weburl` field is "location from which the complete taxonomy source files can be downloaded" with the return value https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy. I have a couple of comments / questions about this:

* first, that wiki page no longer exists (you get the "Create new wiki page" from that link)
* if you search around the opentree wiki, you find this [deprecated OTT page](https://github.com/OpenTreeOfLife/opentree/wiki/|-Open-Tree-Taxonomy---moved) with a link to the https://github.com/OpenTreeOfLife/reference-taxonomy/wiki
* https://github.com/OpenTreeOfLife/reference-taxonomy/wiki doesn't contain any information about how to download complete taxonomy source files (i.e. what is documented for the `weburl` field)

So, we need to change the contents of the `weburl` field **and** make sure the description matches the destination. Can I propose that `weburl` is the "release page for this version of the taxonomy" and returns https://tree.opentreeoflife.org/about/taxonomy-version/ott2.9. 

@jar398 ?

**Comment by jar398** [comment]
That sounds good to me.

I have not reviewed taxonomy metadata at all yet. It occurs in two places:
taxonomy/about, and source tree info in several tree_of_life methods (the
taxonomy being, for some purposes, an honorary source tree).

**Comment by kcranston** [comment]
Are you making this change, @jar398 ? Should I make an issue in the taxomachine repo?

**Comment by jar398** [comment]
This is a good change but currently this information is baked into the
database. It needs to either be altered on its way out (either in
Taxonomy.getMetadataMap.java or in plugins/taxonomy_v3.java) or we need to
build a new database, which would be a nuisance.

The 'about' results should also be made to be a superset of the
tree_of_life support/conflict taxonomy metadata fields. That's a separate
issue but we may as well do both at the same time. I'll assign this issue
to me and do it in the next couple of days.

**Comment by jar398** [comment]
Seems to be fixed:

    $ curl -X POST -H "Content-Type":"application/json" https://devapi.opentreeoflife.org/v3/taxonomy/about --data '{}'
    {
      "weburl" : "https://tree.opentreeoflife.org/about/taxonomy-version/ott2.9",
      "author" : "open tree of life project",
      "name" : "ott",
      "source" : "ott2.9draft12",
      "version" : "2.9"
    }

**Comment by kcranston** [comment]
I see some new fields there now, too. Off to update the docs...

(what is the definition of "source" in this context?)

**Comment by jar398** [comment]
source is the full identifying info for the taxonomy (name + major + minor + point, where point release .5 is written 'draft5').  Maybe not the best name; inherited from v2. Propinquity calls it `taxonomy_version`.

(I'm not too keen on 'weburl' either)

**Comment by kcranston** [comment]
[docs changed](https://github.com/OpenTreeOfLife/germinator/wiki/Taxonomy-API-v3#about_taxonomy)
