### ISSUE TITLE
A name is not a synonym of itself - spec clarification

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#62]
I took the liberty of implementing the `synonyms` field in the taxonomy and tnrs APIs as returning a list not containing the name of which the members are synonyms.  This seems reasonable to me and in line with the name of the field.

However, this is a change relative to v2. In v2 the `synonyms` list includes all names. (It should have been called `names`.) If we decide to keep it (opinion?) then the release notes should probably say that there is a difference.

In either case, the documentation should explain what the return value is.

**Comment by kcranston** [comment]
Your change sounds good to me. I will update the release notes (I just checked, and the docs do not mention this behaviour, so no change there).
