### ISSUE TITLE
'list_terminal_descendants' really ought to be 'include_terminal_descendants'

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#63]
The v3 API spec includes a field `list_terminal_descendants`.  To be consistent with other similar boolean fields controlling inclusion of information in the result, the name ought to be `include_terminal_descendants`.

I know it's late to be suggesting API changes (why didn't I catch this sooner?) but it would be very easy to make this change now. The implementation is currently per spec so if we decide on no change, no action is required.

**Comment by kcranston** [comment]
I am ok with changing this. I'll change docs, you change code & tests?

**Comment by kcranston** [comment]
[Docs changed](https://github.com/OpenTreeOfLife/germinator/wiki/Taxonomy-API-v3#taxon_info)

**Comment by jar398** [comment]
Implementation and test updated
