### ISSUE TITLE
mrca results must include a source_id_map

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#68]
In addition to `mrca` and optional `nearest_taxon`, the `mrca` method needs to return a `source_id_map`, since the node-blob will contain support/conflict properties.

(This is really minor, but we said we'd do all spec changes as issues.)

**Comment by kcranston** [comment]
It looks like this is done in the code. Docs are changed. Is there a test for this?

**Comment by jar398** [comment]
There's a syntactic check. (no check to make sure it's the right source id
map.)
