### ISSUE TITLE
Change fuzzy matching default from true to false?

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#69]
Fuzzy matching is much more expensive, so maybe it should not be the default case (as it is in v2).
See https://github.com/OpenTreeOfLife/feedback/issues/242 .

This would be a spec change.

**Comment by kcranston** [comment]
This seems fine with me (I assume you assigned me to make a decision, not to do the implementation?)

**Comment by jar398** [comment]
that's right, was looking for a decision.​ thanks

**Comment by kcranston** [comment]
[Docs changed](https://github.com/OpenTreeOfLife/germinator/wiki/TNRS-API-v3#match_names)

**Comment by jar398** [comment]
Implemented and deployed on v3, but not tested (but it's hard to see how it could go wrong).
