### ISSUE TITLE
Make OTI tree ids consistent with propinquity / treemachine?

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#72]
OTI currently has:

				// create a unique tree id by including the study id, this is the convention from treemachine
				String treeUniqueId = studyId + "_" + treeId;

yielding in query results

      "oti_tree_id" : "pg_1575_tree3164",

Shouldn't these be changed to be consistent with the tree ids generated by propinquity and relayed by tm-lite?  I.e.

				String treeUniqueId = studyId + "@" + treeId;
      "oti_tree_id" : "pg_1575@tree3164",

(Assigning to @kcranston for judgment. Implementation requires changing that one line, plus rebuilding the index.)

**Comment by kcranston** [comment]
I don't think this is a bad idea, but I am increasingly worried about the
expanding scope of v3. We did say that the study methods weren't changing
in this release. I lean towards leaving this for v4.

**Comment by kcranston** [comment]
Actually, I am less certain about this being a needed change. TreeId@StudyId
is simply an opaque string used within the results if an API call.

**Comment by jar398** [comment]
1. but treeid_studyid in OTI results is *not* opaque in OTI calls; there is no other way to find out the id for the tree within the study. This id is absolutely necessary for any subsequent use of the tree.

2. Experience shows that it doesn't matter if you tell someone in the documentation that a field is 'opaque'; nobody reads documentation, and if it looks like it can be parsed or interpreted, it will be parsed or interpreted.

But I'm ok with waiting until after the v3 release to fix this. It doesn't have to wait until v4, even, since one can put better metadata under new properties in the result.

**Comment by jimallman** [comment]
> treeid_studyid in OTI results is not opaque in OTI calls; there is no other way to find out the id for the tree within the study. This id is absolutely necessary for any subsequent use of the tree.

Indeed, we [split the new format in the client-side tree viewer](https://github.com/OpenTreeOfLife/opentree/pull/898/files#diff-1d1b3781103cc75f284db30d76bcd6e8R1353), since there's no other way to retrieve these ids:
```javascript
    var keyParts = key.split('@');
    props.studyID = keyParts.shift();
    // Next value should be the supporting tree id
    props.treeID = keyParts.shift();
```

**Comment by jar398** [comment]
Jim, if you're talking about a syntax with an @, then it came from
propinquity, and does not need to be parsed, since the study and tree ids
are in the source id map.

The combined ids coming from OTI, which one *does* need to parse, look like
studyid_treeid.
