### ISSUE TITLE
Figure out how to avoid test support code duplication across repos

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#74]
e.g. opentreetesting.py, check.py

See https://gitter.im/OpenTreeOfLife/public?at=5705256604930a3b68f646c9

**Comment by jar398** [comment]
See discussion here re http: https://github.com/OpenTreeOfLife/oti/pull/52

**Comment by jar398** [comment]
In addressing this issue, please also review what happens if someone gives http: in an API endpoint, and also review whether 's' works (see comments referenced above)

**Comment by kcranston** [comment]
Looks like there is divergence between the various copies of `run_tests.sh` and `opentreetesting.py`. What if we solved this by setting up the testing code as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules)?

**Comment by kcranston** [comment]
If we did this, are the copies of the testing files in this repo (i.e. germinator) the canonical ones?

**Comment by jar398** [comment]
Maybe. Seems like a bit of overkill when we're only talking about two or three files. As far as I know the germinator versions are the 'master' versions and anything else is a local cache, perhaps stale. If we could rely on there being a germinator repo clone somewhere, one could just run run_tests.sh out of germinator.

**Comment by kcranston** [comment]
If we went that route, then should the location of the germinator repo be in `test.conf` and the copies of `run_tests.sh` and `opentreetesting.py` be deleted from the other repos?

**Comment by jar398** [comment]
Options
1. Assume everyone has cloned germinator. Shared test files go there and there are no copies in other repos. Optional: some common (as opposed to personal) way to abbreviate the common command '../germinator/ws-tests/run_tests.sh ...'
2. Submodule. Everyone clones the submodule. Shared test files go in submodule and there are no copies in other repos. Optional: some common way to abbreviate the command '{submodule}/{something}/run_tests.sh ...'
The two are pretty much the same. The disadvantage of 1. is that we end up with this tiny 3-file repository. The disadvantage of 2. is that we don't have the support that git provides for submodules (which I do not know much about).

**Comment by kcranston** [comment]
Let's go with option 1 and not futz with submodules. Germinator holds `opentreetesting.py` and `run_tests.sh` and the copies in other repos get deleted. The test instructions in other repos then look something this: [TESTING.md in otindex](https://github.com/OpenTreeOfLife/otindex/blob/master/TESTING.md) ? Anything else?

**Comment by mtholder** [comment]
seems like we made a decision and this is what we are doing...
