### ISSUE TITLE
Missing doc change with taxonomy/mrca?

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/germinator#79]
taxonomy/lica used to have a ["include_lineage"](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#lica) arg. the new taxonomy/mrca does not have this arg, but the [release notes](https://github.com/OpenTreeOfLife/germinator/wiki/Release-notes-for-web-API-v3) do not mention this. is this an error?

**Comment by josephwb** [comment]
This is [in the code](https://github.com/OpenTreeOfLife/taxomachine/blob/v3/src/main/java/org/opentree/taxonomy/plugins/taxonomy_v3.java#L117-L121), so does look like another documentation problem.

**Comment by jar398** [comment]
added comment on this to release notes.
