### ISSUE TITLE
multiple failures in ws tests

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/germinator#83]
I just ran the test suite in germinator (`bash run_tests.sh http://api.opentreeoflife.org`) and had multiple  failures - more failures than successes. I did pull the master branch on each repo in advance. Failures:

* phylesystem-api
   * test_study_get_bad_outformat.py 
   * test_study_get_multiformat.py 
   * test_tree_newick_get.py 
   * test_v2_studies_find_trees.py
* treemachine (all tests failed)
* taxomachine (>20 failures)
* oti: test_basic.py failed (which looks to be the only test)

Is this expected? If so, then we need a better testing process (both for running tests and for keeping tests up-to-date). If not, then we have an API problem.

**Comment by kcranston** [comment]
@jar398 Any thoughts on this? Someone was asking me about a failing API method, which led me to run the tests and then made me sad that I could not triumphantly say "they are all passing for me".

**Comment by jar398** [comment]
will look into it. they all passed for me last time I tried, so it may be
that I failed to check some things in.

**Comment by jar398** [comment]
I think you will have to give me more detail, since all tests pass for me, and the only repo with uncommitted files was oti (see PR). And I pulled all the repos. My test was: 

    cd ../germinator/ws-tests/
    ./run_tests.sh https://api.opentreeoflife.org

Try 'export VERBOSITY_LEVEL=1' before running, then send me the output you see in the shell buffer.

Could be a python version problem or something? I'm running 2.7.5.

**Comment by kcranston** [comment]
Ok, thanks. Issue was http vs https. I've made a PR so that the script checks for this...
