### ISSUE TITLE
(Taxon addition feature) Terminology quibble: the source of a taxon, not evidence for it

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/germinator#91]
Instead of 'evidence for taxon' I suggest 'taxon source' since 'evidence' is not semantically appropriate here.

(One finds evidence for a claim, or for the _existence_ of a taxon, but not for a taxon per se. The existence of the taxon is not in dispute, and anyhow it can't be in dispute until we know what taxon is under discussion. 'Source' is also sort of funny but not nearly as bad since it admits to metonymy: to know what taxon we're talking about, one checks a source that gives information about the taxon, expressed using the taxon's name.)

**Comment by mtholder** [comment]
fixed, but issue was not closed
